apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: cts-inventory
  name: REPLACEME_NAME
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
    - hosts:
        - "REPLACEME_HOST"
      secretName: "REPLACEME_NAME"
  rules:
    - host: "REPLACEME_HOST"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: "REPLACEME_SERVICE"
              servicePort: 80